name: pytest

on:
  push:
    branches:
      - 'master'
      - 'stage'

jobs:
  pytest:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: Aa123456
          POSTGRES_USER: postgres
          POSTGRES_DB: project

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-github-report
      - name: Report via Environment
        env:
          pytest_github_report: true
          pytest_report_title: ":unicorn: Report With Custom Emojis :unicorn:"
          pytest_passed_emoji: ":green_heart:"
          pytest_failed_emoji: ":heart:"
          pytest_xpassed_emoji: ":bangbang:"
          pytest_xfailed_emoji: ":bangbang:"
          pytest_skipped_emoji: ":shipit:"
        run: pytest tests